### ISSUE TITLE
How to Serialize?

### ISSUE THREAD

**Issue by rondymesquita** [northwesternmutual/regent#38]
Hi! This is not a issue itself, it more like a question.
Is there any way to serialize the rule to, for instance, save on database and load it in a later time?
Thanks.

**Comment by eisenivan** [comment]
Regent 1 and 2 both support this by defining the rules in a JSON structure natively. An import / export is on the backlog in regent 3.

**Comment by eisenivan** [comment]
@rondymesquita ^^

**Comment by rondymesquita** [comment]
Awesome! thanks for the info.

**Comment by eisenivan** [comment]
Closing this issue because I think we're all good. Don't hesitate to reach out with any other questions. I actually genuinely enjoy answering them :)

**Comment by eisenivan** [comment]
@rondymesquita you have inspired me. I started working on this feature today. Going well so far :)

I have created an enhancement with some sample data. Would this fit your use case?

https://github.com/northwesternmutual/regent/issues/39

**Comment by rondymesquita** [comment]
WOW, That is awesome! I will take a look a soon as possible. Thanks for the update.

**Comment by rondymesquita** [comment]
Can I get involved into discussions?
